// components/Cell.vue
<script setup lang="ts">
import { formattedDate } from '@/utils'

interface Article {
  _path: string
  title: string
  date: string
}

const { article } = defineProps<{ article: Article }>()
</script>

<template>
  <NuxtLink :to="`/p${article._path}`" class="group block p-4 rounded-xl mb-4 transition-all duration-300 hover-lift glass-card">
    <li
      :title="article.title"
      class="grid grid-cols-3 gap-4 items-center"
    >
      <span class="col-span-2 basis-3/6 grow text-lg font-medium truncate text-ellipsis overflow-hidden text-[var(--primary)] group-hover:text-[#4a7c6f] transition-colors duration-300">
        {{ article.title }}
      </span>
      <span class="col-span-1 basis-1/6" />
      <span class="col-span-1 basis-2/6 text-sm text-[var(--text-secondary)] group-hover:text-[#4a7c6f] transition-colors duration-300">
        {{ formattedDate(article.date) }}
        <span class="i-icon-park-outline-arrow-right ml-2 op-0 group-hover:op-100 transition-all duration-300 inline-block w-4 h-4"></span>
      </span>
    </li>
  </NuxtLink>
</template>

<style scoped>
.group:hover {
  border-color: var(--common-bd);
}
</style>

// components/Cell.tsx
import Link from "next/link"
import type { ManifestPost } from "@/lib/r2"

export default function Cell({ post }: { post: ManifestPost }) {
  return (
    <Link href={post.path} className="block rounded-lg border border-[var(--border-subtle)] p-4 hover:border-[var(--primary)] transition-colors">
      <h3 className="text-base font-medium">{post.title}</h3>
      <div className="mt-1 flex items-center gap-3 text-xs text-[var(--text-secondary)]">
        {post.date && <time>{post.date}</time>}
        {post.tags.length > 0 && (
          <span className="flex gap-1">
            {post.tags.slice(0, 3).map(t => <span key={t} className="rounded bg-[var(--bg-card)] px-1.5 py-0.5">{t}</span>)}
          </span>
        )}
      </div>
      {post.description && <p className="mt-2 text-sm text-[var(--text-secondary)] line-clamp-2">{post.description}</p>}
    </Link>
  )
}
